=== inf25tig05/museu-digital-multimedia/sala-imagem.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="textoLetrasType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-zÀ-ÿ ]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="anoType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{4}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="posicaoType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="quadro-esquerda"/>
      <xs:enumeration value="quadro-centro"/>
      <xs:enumeration value="quadro-direita"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="obras">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="obra" maxOccurs="3">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="textoLetrasType"/>
              <xs:element name="autor" type="textoLetrasType"/>
              <xs:element name="ano_nascimento_autor" type="anoType"/>
              <xs:element name="ano_morte_autor" type="anoType"/>
              <xs:element name="ano_obra" type="anoType"/>
              <xs:element name="imagem" type="xs:string"/>
              <xs:element name="descricao" type="xs:string"/>
            </xs:sequence>

            <xs:attribute name="posicao" type="posicaoType" use="required"/>

          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== inf25tig05/museu-digital-multimedia/sala-imagem.xml
<?xml version="1.0" encoding="UTF-8"?>

<obras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="sala-imagem.xsd">

  <obra posicao="quadro-esquerda">
    <titulo>A Escola de Atenas</titulo>
    <autor>Rafael Sanzio</autor>
    <ano_nascimento_autor>1483</ano_nascimento_autor>
    <ano_morte_autor>1520</ano_morte_autor>
    <imagem>img/obras/a-escola-de-atenas.jpg</imagem>
    <descricao>Obra renascentista que representa filósofos e pensadores da Antiguidade.</descricao>
  </obra>

  <obra posicao="quadro-centro">
    <titulo>Santa Ceia</titulo>
    <autor>Leonardo da Vinci</autor>
    <ano_nascimento_autor>1452</ano_nascimento_autor>
    <ano_morte_autor>1519</ano_morte_autor>
    <imagem>img/obras/santa-ceia.jpg</imagem>
    <descricao>Representação do momento da última refeição de Cristo com os seus discípulos.</descricao>
  </obra>

  <obra posicao="quadro-direita">
    <titulo>Viagem a Lua</titulo>
    <autor>Georges Melies</autor>
    <ano_nascimento_autor>1861</ano_nascimento_autor>
    <ano_morte_autor>1938</ano_morte_autor>
    <imagem>img/obras/viagem-a-lua.jpg</imagem>
    <descricao>Obra marcante da história do cinema, associada ao imaginário da viagem espacial.</descricao>
  </obra>

</obras>
